AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    AWS Serverless Application for Trend Micro security hub

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
    Function:
        Timeout: 30



Resources:

    DSSecurityHubFunction:
        Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
        Properties:
            CodeUri: ds-aws-security-hub/
            Handler: ds_aws_security_hub.lambda_handler
            Runtime: python3.6
            Role: arn:aws:iam::650143975734:role/awspydssecurityhubus
            Events:
                DSEvent:
                    Type: SNS
                    Properties:
                      Topic:
                        Ref: SNSTopic1

    SNSTopic1:
        Type: 'AWS::SNS::Topic'
